version: "3.8"

services:
  go:
    build: .
    container_name: go
    restart: on-failure
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: db
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=todo1234
      - MYSQL_DATABASE=todo
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=todo1234
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
    my-db: